<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="15345" started-at="2018-07-25T07:02:39Z" finished-at="2018-07-25T07:02:55Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="737" started-at="2018-07-25T07:02:39Z" finished-at="2018-07-25T07:02:40Z">
      <class name="com.accenture.test.LoginTest">
        <test-method status="FAIL" signature="LoginInvalid()[pri:0, instance:com.accenture.test.LoginTest@4cb2c100]" name="LoginInvalid" duration-ms="15" started-at="2018-07-25T12:32:40Z" finished-at="2018-07-25T12:32:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Tested] but found [Tested123]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Tested] but found [Tested123]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.accenture.test.LoginTest.LoginInvalid(LoginTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginInvalid -->
        <test-method status="PASS" signature="LoginValid()[pri:0, instance:com.accenture.test.LoginTest@4cb2c100]" name="LoginValid" duration-ms="1" started-at="2018-07-25T12:32:40Z" finished-at="2018-07-25T12:32:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginValid -->
      </class> <!-- com.accenture.test.LoginTest -->
    </test> <!-- Test1 -->
    <test name="Test2" duration-ms="13890" started-at="2018-07-25T07:02:41Z" finished-at="2018-07-25T07:02:55Z">
      <class name="com.accenture.test.Registeration_test">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.accenture.test.Registeration_test@b97c004]" name="beforeTest" is-config="true" duration-ms="10622" started-at="2018-07-25T12:32:41Z" finished-at="2018-07-25T12:32:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="TestRegstr()[pri:0, instance:com.accenture.test.Registeration_test@b97c004]" name="TestRegstr" duration-ms="3266" started-at="2018-07-25T12:32:52Z" finished-at="2018-07-25T12:32:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestRegstr -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.accenture.test.Registeration_test@b97c004]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-07-25T12:32:55Z" finished-at="2018-07-25T12:32:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.accenture.test.Registeration_test -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
