<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P4A-508SD4B" name="Test1" tests="2" failures="1" timestamp="25 Jul 2018 07:02:40 GMT" time="0.737" errors="0">
  <testcase name="LoginInvalid" time="0.015" classname="com.accenture.test.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [Tested] but found [Tested123]">
      <![CDATA[java.lang.AssertionError: expected [Tested] but found [Tested123]
	at com.accenture.test.LoginTest.LoginInvalid(LoginTest.java:19)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- LoginInvalid -->
  <testcase name="LoginValid" time="0.001" classname="com.accenture.test.LoginTest"/>
</testsuite> <!-- Test1 -->
